# setting up a conda environment for a simple python app
# using this app for playing around with docker container
# and then for testing with pytest
# and gitlab CI/CD in a further step
# conda env update --file environment.yml --prune

name: homevocab 
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11.5
  - pip
  - jinja2
  - unidecode
  - qrcode
  - python-dotenv
  - fastapi
  - uvicorn-standard
