#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Mar 21 09:10:32 2025

@author: bernd
"""
from .base import ExportConfig
import os

"""
    Make Configs here:
    ExportConfig:
        column_map: key=csv column name, value=the output markdown colum name
                    columns in this dictionary will be displayed. Add key-value
                    pairs on demand.
        csv_path:   source path of csv
        dest_path:  destination path for the markdown file (e.g. the obsidian vault)
        file_prefix:put this as prefix of the markdown file
        sortby:     data will be sorted A-Z ascending along this column
        tag_prefix: helps to identify tag-columns from the one hot encoded csv
                    e.g.: tag_prefix = "_" --> all column names starting with "_"
                    will be considered as tag column. 
"""
    
used_conf = ExportConfig(
    column_map={
        "id":"id",
        "right":"neměcký",
        "left":"český",
        "info_left":"info",
        },
    csv_path=os.getenv('CSV_SOURCE'),
    dest_path=os.getenv('MD_PATH'),
    file_prefix='autogenerated-vocabfile-',
    sortby='left',
    tag_prefix="_"
    )

